In [3]:
import pandas as pd
df=pd.read_csv('OnlineRetail.csv', encoding = "ISO-8859-1")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
#Đọc bộ dữ liệu, cho biết số dòng, số cột và kiểu dữ liệu của các thuộc tính.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [8]:
#Tạo cột mới có tên quý –  ‘Previous’ nhận giá trị 1 nếu ngày lập hóa đơn nằm trong các tháng 1,2,3; nhận giá trị 2 nếu ngày lập hóa đơn nằm trong các tháng 4,5,6; nhận giá trị 3 nếu ngày lập hóa đơn nằm trong các tháng 7,8,9;  nhận giá trị 4 nếu ngày lập hóa đơn nằm trong các tháng 10,11,12;

# Chuyển đổi cột 'InvoiceDate' thành định dạng datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
# Tạo cột 'Previous' dựa trên giá trị tháng
df['Previous'] = df['InvoiceDate'].dt.month.map({
    1: 1, 2: 1, 3: 1,
    4: 2, 5: 2, 6: 2,
    7: 3, 8: 3, 9: 3,
    10: 4, 11: 4, 12: 4
})

print(df[['InvoiceDate', 'Previous']])

               InvoiceDate  Previous
0      2010-12-01 08:26:00         4
1      2010-12-01 08:26:00         4
2      2010-12-01 08:26:00         4
3      2010-12-01 08:26:00         4
4      2010-12-01 08:26:00         4
...                    ...       ...
541904 2011-12-09 12:50:00         4
541905 2011-12-09 12:50:00         4
541906 2011-12-09 12:50:00         4
541907 2011-12-09 12:50:00         4
541908 2011-12-09 12:50:00         4

[541909 rows x 2 columns]

In [9]:
#Tạo một cột mới có tên ‘Amount’ có giá trị bằng Quantity * UnitPrice
df['Amount'] = df['Quantity'] * df['UnitPrice']
print(df[['Quantity', 'UnitPrice', 'Amount']])

        Quantity  UnitPrice  Amount
0              6       2.55   15.30
1              6       3.39   20.34
2              8       2.75   22.00
3              6       3.39   20.34
4              6       3.39   20.34
...          ...        ...     ...
541904        12       0.85   10.20
541905         6       2.10   12.60
541906         4       4.15   16.60
541907         4       4.15   16.60
541908         3       4.95   14.85

[541909 rows x 3 columns]

In [13]:
#Tạo cột mới ‘Discount’ nhận giá trị 10% nếu Country là ‘United Kingdom’ và thuộc quý 4, 5% nếu là ‘France’ ngược lại là 0%.
df['Discount'] = 0
df.loc[(df['Country'] == 'United Kingdom') & (df['Previous'] == 4), 'Discount'] = 0.10
df.loc[df['Country'] == 'France', 'Discount'] = 0.05
print(df[['Country', 'Previous', 'Discount']])

               Country  Previous  Discount
0       United Kingdom         4      0.10
1       United Kingdom         4      0.10
2       United Kingdom         4      0.10
3       United Kingdom         4      0.10
4       United Kingdom         4      0.10
...                ...       ...       ...
541904          France         4      0.05
541905          France         4      0.05
541906          France         4      0.05
541907          France         4      0.05
541908          France         4      0.05

[541909 rows x 3 columns]

<ipython-input-13-849cedef4765>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['Country'] == 'United Kingdom') & (df['Previous'] == 4), 'Discount'] = 0.10

In [12]:
#Tạo cột mới ‘Total’ nhận giá trị bằng: Amount – Discount.
df['Total'] = df['Amount'] - (df['Amount'] * df['Discount'])
print(df[['Amount', 'Discount', 'Total']])

        Amount  Discount    Total
0        15.30      0.10  13.7700
1        20.34      0.10  18.3060
2        22.00      0.10  19.8000
3        20.34      0.10  18.3060
4        20.34      0.10  18.3060
...        ...       ...      ...
541904   10.20      0.05   9.6900
541905   12.60      0.05  11.9700
541906   16.60      0.05  15.7700
541907   16.60      0.05  15.7700
541908   14.85      0.05  14.1075

[541909 rows x 3 columns]