In [2]:
import pandas as pd
df=pd.read_csv('OnlineRetail.csv', encoding='latin')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
#Đọc bộ dữ liệu, cho biết số dòng, số cột và kiểu dữ liệu của các thuộc tính.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [7]:
#Xây dựng bảng Pivot table, với mỗi Số hóa đơn tính trung bình cộng số lượng các mặt hàng theo từng Quốc gia.
pivot_table=pd.pivot_table(df, values='Quantity', index='InvoiceNo', columns='Country', aggfunc='mean', fill_value=0)
print(pivot_table)

Country    Australia  Austria  Bahrain  Belgium  Brazil  Canada  \
InvoiceNo
536365           0.0      0.0      0.0      0.0     0.0     0.0
536366           0.0      0.0      0.0      0.0     0.0     0.0
536367           0.0      0.0      0.0      0.0     0.0     0.0
536368           0.0      0.0      0.0      0.0     0.0     0.0
536369           0.0      0.0      0.0      0.0     0.0     0.0
...              ...      ...      ...      ...     ...     ...
C581484          0.0      0.0      0.0      0.0     0.0     0.0
C581490          0.0      0.0      0.0      0.0     0.0     0.0
C581499          0.0      0.0      0.0      0.0     0.0     0.0
C581568          0.0      0.0      0.0      0.0     0.0     0.0
C581569          0.0      0.0      0.0      0.0     0.0     0.0

Country    Channel Islands  Cyprus  Czech Republic  Denmark  ...  RSA  \
InvoiceNo                                                    ...
536365                 0.0     0.0             0.0      0.0  ...  0.0
536366                 0.0     0.0             0.0      0.0  ...  0.0
536367                 0.0     0.0             0.0      0.0  ...  0.0
536368                 0.0     0.0             0.0      0.0  ...  0.0
536369                 0.0     0.0             0.0      0.0  ...  0.0
...                    ...     ...             ...      ...  ...  ...
C581484                0.0     0.0             0.0      0.0  ...  0.0
C581490                0.0     0.0             0.0      0.0  ...  0.0
C581499                0.0     0.0             0.0      0.0  ...  0.0
C581568                0.0     0.0             0.0      0.0  ...  0.0
C581569                0.0     0.0             0.0      0.0  ...  0.0

Country    Saudi Arabia  Singapore  Spain  Sweden  Switzerland  USA  \
InvoiceNo
536365              0.0        0.0    0.0     0.0          0.0  0.0
536366              0.0        0.0    0.0     0.0          0.0  0.0
536367              0.0        0.0    0.0     0.0          0.0  0.0
536368              0.0        0.0    0.0     0.0          0.0  0.0
536369              0.0        0.0    0.0     0.0          0.0  0.0
...                 ...        ...    ...     ...          ...  ...
C581484             0.0        0.0    0.0     0.0          0.0  0.0
C581490             0.0        0.0    0.0     0.0          0.0  0.0
C581499             0.0        0.0    0.0     0.0          0.0  0.0
C581568             0.0        0.0    0.0     0.0          0.0  0.0
C581569             0.0        0.0    0.0     0.0          0.0  0.0

Country    United Arab Emirates  United Kingdom  Unspecified
InvoiceNo
536365                      0.0        5.714286          0.0
536366                      0.0        6.000000          0.0
536367                      0.0        6.916667          0.0
536368                      0.0        3.750000          0.0
536369                      0.0        3.000000          0.0
...                         ...             ...          ...
C581484                     0.0   -80995.000000          0.0
C581490                     0.0      -11.500000          0.0
C581499                     0.0       -1.000000          0.0
C581568                     0.0       -5.000000          0.0
C581569                     0.0       -3.000000          0.0

[25900 rows x 38 columns]

In [9]:
#Xây dựng bảng Pivot table, với mỗi Khách hàng cho biết số lượng mua hàng lớn nhất và nhỏ nhất theo Kho.
pivot_table=pd.pivot_table(df, values='Quantity', index='CustomerID', columns='StockCode', aggfunc={min, max}, fill_value=0)
print(pivot_table)

<ipython-input-9-eff2d7e2fcc2>:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pivot_table=pd.pivot_table(df, values='Quantity', index='CustomerID', columns='StockCode', aggfunc={min, max}, fill_value=0)
<ipython-input-9-eff2d7e2fcc2>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pivot_table=pd.pivot_table(df, values='Quantity', index='CustomerID', columns='StockCode', aggfunc={min, max}, fill_value=0)

             max                                                           \
StockCode  10002 10080 10120 10123C 10124A 10124G 10125 10133 10135 11001
CustomerID
12346.0        0     0     0      0      0      0     0     0     0     0
12347.0        0     0     0      0      0      0     0     0     0     0
12348.0        0     0     0      0      0      0     0     0     0     0
12349.0        0     0     0      0      0      0     0     0     0     0
12350.0        0     0     0      0      0      0     0     0     0     0
...          ...   ...   ...    ...    ...    ...   ...   ...   ...   ...
18280.0        0     0     0      0      0      0     0     0     0     0
18281.0        0     0     0      0      0      0     0     0     0     0
18282.0        0     0     0      0      0      0     0     0     0     0
18283.0        0     0     0      0      0      0     0     0     0     0
18287.0        0     0     0      0      0      0     0     0     0     0

            ...    min
StockCode   ... 90214Y 90214Z BANK CHARGES C2 CRUK  D DOT  M PADS POST
CustomerID  ...
12346.0     ...      0      0            0  0    0  0   0  0    0    0
12347.0     ...      0      0            0  0    0  0   0  0    0    0
12348.0     ...      0      0            0  0    0  0   0  0    0    1
12349.0     ...      0      0            0  0    0  0   0  0    0    1
12350.0     ...      0      0            0  0    0  0   0  0    0    1
...         ...    ...    ...          ... ..  ... ..  .. ..  ...  ...
18280.0     ...      0      0            0  0    0  0   0  0    0    0
18281.0     ...      0      0            0  0    0  0   0  0    0    0
18282.0     ...      0      0            0  0    0  0   0  0    0    0
18283.0     ...      0      0            0  0    0  0   0  1    0    0
18287.0     ...      0      0            0  0    0  0   0  0    0    0

[4372 rows x 7368 columns]

In [13]:
#Xây dựng bảng Pivot table, với mỗi Mã kho tính tổng số lượng các mặt hàng và trung bình cộng giá.
pivot_table_sum=pd.pivot_table(df, values='Quantity', index='StockCode', aggfunc='sum', fill_value=0)
pivot_table_mean=pd.pivot_table(df, values='UnitPrice', index='StockCode', aggfunc='mean', fill_value=0)
print(pivot_table_sum)
print(pivot_table_mean)

              Quantity
StockCode
10002             1037
10080              495
10120              193
10123C             -13
10123G             -38
...                ...
gift_0001_20        20
gift_0001_30        37
gift_0001_40         3
gift_0001_50         4
m                    1

[4070 rows x 1 columns]
              UnitPrice
StockCode
10002          1.056849
10080          0.376667
10120          0.210000
10123C         0.487500
10123G         0.000000
...                 ...
gift_0001_20  15.038000
gift_0001_30  21.941250
gift_0001_40  33.566667
gift_0001_50  41.890000
m              2.550000

[4070 rows x 1 columns]

In [14]:
#Xây dựng bảng Pivot table cho biết tổng số lượng hàng bán được của mỗi ngày.
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])
pivot_table=pd.pivot_table(df, values='Quantity', index='InvoiceDate', aggfunc='sum', fill_value=0)
print(pivot_table)

                     Quantity
InvoiceDate
2010-12-01 08:26:00        40
2010-12-01 08:28:00        12
2010-12-01 08:34:00        98
2010-12-01 08:35:00         3
2010-12-01 08:45:00       449
...                       ...
2011-12-09 12:23:00        76
2011-12-09 12:25:00       120
2011-12-09 12:31:00       278
2011-12-09 12:49:00        66
2011-12-09 12:50:00       105

[23260 rows x 1 columns]